### ISSUE TITLE
Openrouter keys no longer checking

### ISSUE THREAD

**Issue by elinorgodzilla** [cunnymessiah/keychecker#8]
I re-post this since the problem now seems to be persistent. 
Error is when checking Openrouter api key:
"Unexpected error occurred for key sk-or-v1-xxx: 'NoneType' object is not subscriptable"
Seems like Openrouter changed something on their end. Happens on any key, be it paid or free.

**Comment by cunnymessiah** [comment]
fixed, but the problem is that openrouter now stops returning the `per_request_limits` object in the models response, which makes the calculation for balance retrieval impossible.

https://openrouter.ai/docs/limits
the property is still listed in their docs so maybe they will re-add it in the future.

**Comment by elinorgodzilla** [comment]
Thank you so much for the workaround and the explanation. Appreciated!
